name: Deploy Static Site

on:
  push:
    branches:
      - main
    paths:
      - '**.dsl'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Download Structurizr CLI
        run: |
          curl -L -o structurizr-cli.zip https://github.com/structurizr/cli/releases/latest/download/structurizr-cli.zip
          unzip structurizr-cli.zip -d structurizr-cli
          chmod +x structurizr-cli/structurizr.sh

      - name: install Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz

      - name: Compile static site with Structurizr
        run: |
          ./structurizr-cli/structurizr.sh export -workspace workspace.dsl -format static -output ./static-site

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Deploy to S3
        run: |
          aws s3 sync ./static-site s3://glen-thomas-structurizr-blog-static-site/ --delete